# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0014_decide_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=3, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(default='First name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default='Last name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='State', max_length=100),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='decisions.Decide'),
        ),
        migrations.AlterField(
            model_name='item',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='decisions.Decide'),
        ),
    ]
