# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0016_auto_20171120_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
