minScore = 8.0
maxScore = 9.2
minYear = 1921
maxYear = 2017
MOVIES = [{'title': 'The Shawshank Redemption', 'IMDB Score': '9.2', 'Year of Release': '1994'},
{'title': 'The Godfather', 'IMDB Score': '9.2', 'Year of Release': '1972'},
{'title': 'The Godfather: Part II', 'IMDB Score': '9.0', 'Year of Release': '1974'},
{'title': 'The Dark Knight', 'IMDB Score': '9.0', 'Year of Release': '2008'},
{'title': '12 Angry Men', 'IMDB Score': '8.9', 'Year of Release': '1957'},
{'title': "Schindler's List", 'IMDB Score': '8.9', 'Year of Release': '1993'},
{'title': 'The Lord of the Rings: The Return of the King', 'IMDB Score': '8.9', 'Year of Release': '2003'},
{'title': 'Pulp Fiction', 'IMDB Score': '8.9', 'Year of Release': '1994'},
{'title': 'The Good, the Bad and the Ugly', 'IMDB Score': '8.8', 'Year of Release': '1966'},
{'title': 'Fight Club', 'IMDB Score': '8.8', 'Year of Release': '1999'},
{'title': 'The Lord of the Rings: The Fellowship of the Ring', 'IMDB Score': '8.8', 'Year of Release': '2001'},
{'title': 'Forrest Gump', 'IMDB Score': '8.7', 'Year of Release': '1994'},
{'title': 'Star Wars: Episode V - The Empire Strikes Back', 'IMDB Score': '8.7', 'Year of Release': '1980'},
{'title': 'Inception', 'IMDB Score': '8.7', 'Year of Release': '2010'},
{'title': 'The Lord of the Rings: The Two Towers', 'IMDB Score': '8.7', 'Year of Release': '2002'},
{'title': "One Flew Over the Cuckoo's Nest", 'IMDB Score': '8.7', 'Year of Release': '1975'},
{'title': 'Goodfellas', 'IMDB Score': '8.7', 'Year of Release': '1990'},
{'title': 'The Matrix', 'IMDB Score': '8.6', 'Year of Release': '1999'},
{'title': 'Seven Samurai', 'IMDB Score': '8.6', 'Year of Release': '1954'},
{'title': 'Star Wars: Episode IV - A New Hope', 'IMDB Score': '8.6', 'Year of Release': '1977'},
{'title': 'City of God', 'IMDB Score': '8.6', 'Year of Release': '2002'},
{'title': 'Se7en', 'IMDB Score': '8.6', 'Year of Release': '1995'},
{'title': 'The Silence of the Lambs', 'IMDB Score': '8.6', 'Year of Release': '1991'},
{'title': "It's a Wonderful Life", 'IMDB Score': '8.6', 'Year of Release': '1946'},
{'title': 'Life Is Beautiful', 'IMDB Score': '8.6', 'Year of Release': '1997'},
{'title': 'The Usual Suspects', 'IMDB Score': '8.6', 'Year of Release': '1995'},
{'title': 'Spirited Away', 'IMDB Score': '8.5', 'Year of Release': '2001'},
{'title': 'Léon: The Professional', 'IMDB Score': '8.5', 'Year of Release': '1994'},
{'title': 'Saving Private Ryan', 'IMDB Score': '8.5', 'Year of Release': '1998'},
{'title': 'Interstellar', 'IMDB Score': '8.5', 'Year of Release': '2014'},
{'title': 'The Green Mile', 'IMDB Score': '8.5', 'Year of Release': '1999'},
{'title': 'American History X', 'IMDB Score': '8.5', 'Year of Release': '1998'},
{'title': 'Psycho', 'IMDB Score': '8.5', 'Year of Release': '1960'},
{'title': 'Once Upon a Time in the West', 'IMDB Score': '8.5', 'Year of Release': '1968'},
{'title': 'City Lights', 'IMDB Score': '8.5', 'Year of Release': '1931'},
{'title': 'Casablanca', 'IMDB Score': '8.5', 'Year of Release': '1942'},
{'title': 'The Intouchables', 'IMDB Score': '8.5', 'Year of Release': '2011'},
{'title': 'Modern Times', 'IMDB Score': '8.5', 'Year of Release': '1936'},
{'title': 'The Pianist', 'IMDB Score': '8.5', 'Year of Release': '2002'},
{'title': 'The Departed', 'IMDB Score': '8.5', 'Year of Release': '2006'},
{'title': 'Raiders of the Lost Ark', 'IMDB Score': '8.5', 'Year of Release': '1981'},
{'title': 'Terminator 2', 'IMDB Score': '8.5', 'Year of Release': '1991'},
{'title': 'Rear Window', 'IMDB Score': '8.5', 'Year of Release': '1954'},
{'title': 'Back to the Future', 'IMDB Score': '8.5', 'Year of Release': '1985'},
{'title': 'Whiplash', 'IMDB Score': '8.5', 'Year of Release': '2014'},
{'title': 'Gladiator', 'IMDB Score': '8.5', 'Year of Release': '2000'},
{'title': 'The Lion King', 'IMDB Score': '8.5', 'Year of Release': '1994'},
{'title': 'The Prestige', 'IMDB Score': '8.5', 'Year of Release': '2006'},
{'title': 'Memento', 'IMDB Score': '8.4', 'Year of Release': '2000'},
{'title': 'Apocalypse Now', 'IMDB Score': '8.4', 'Year of Release': '1979'},
{'title': 'Alien', 'IMDB Score': '8.4', 'Year of Release': '1979'},
{'title': 'The Great Dictator', 'IMDB Score': '8.4', 'Year of Release': '1940'},
{'title': 'Cinema Paradiso', 'IMDB Score': '8.4', 'Year of Release': '1988'},
{'title': 'Sunset Boulevard', 'IMDB Score': '8.4', 'Year of Release': '1950'},
{'title': 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'IMDB Score': '8.4', 'Year of Release': '1964'},
{'title': 'Grave of the Fireflies', 'IMDB Score': '8.4', 'Year of Release': '1988'},
{'title': 'The Lives of Others', 'IMDB Score': '8.4', 'Year of Release': '2006'},
{'title': 'Coco', 'IMDB Score': '8.4', 'Year of Release': '2017'},
{'title': 'Paths of Glory', 'IMDB Score': '8.4', 'Year of Release': '1957'},
{'title': 'The Shining', 'IMDB Score': '8.4', 'Year of Release': '1980'},
{'title': 'Django Unchained', 'IMDB Score': '8.4', 'Year of Release': '2012'},
{'title': 'Princess Mononoke', 'IMDB Score': '8.4', 'Year of Release': '1997'},
{'title': 'American Beauty', 'IMDB Score': '8.4', 'Year of Release': '1999'},
{'title': 'The Dark Knight Rises', 'IMDB Score': '8.4', 'Year of Release': '2012'},
{'title': 'Witness for the Prosecution', 'IMDB Score': '8.4', 'Year of Release': '1957'},
{'title': 'Oldboy', 'IMDB Score': '8.4', 'Year of Release': '2003'},
{'title': 'Aliens', 'IMDB Score': '8.4', 'Year of Release': '1986'},
{'title': 'Once Upon a Time in America', 'IMDB Score': '8.3', 'Year of Release': '1984'},
{'title': 'Das Boot', 'IMDB Score': '8.3', 'Year of Release': '1981'},
{'title': 'Citizen Kane', 'IMDB Score': '8.3', 'Year of Release': '1941'},
{'title': 'North by Northwest', 'IMDB Score': '8.3', 'Year of Release': '1959'},
{'title': 'Vertigo', 'IMDB Score': '8.3', 'Year of Release': '1958'},
{'title': 'Braveheart', 'IMDB Score': '8.3', 'Year of Release': '1995'},
{'title': 'Reservoir Dogs', 'IMDB Score': '8.3', 'Year of Release': '1992'},
{'title': 'Star Wars: Episode VI - Return of the Jedi', 'IMDB Score': '8.3', 'Year of Release': '1983'},
{'title': 'Dangal', 'IMDB Score': '8.3', 'Year of Release': '2016'},
{'title': 'M', 'IMDB Score': '8.3', 'Year of Release': '1931'},
{'title': 'Your Name', 'IMDB Score': '8.3', 'Year of Release': '2016'},
{'title': 'Requiem for a Dream', 'IMDB Score': '8.3', 'Year of Release': '2000'},
{'title': 'Like Stars on Earth', 'IMDB Score': '8.3', 'Year of Release': '2007'},
{'title': 'Amadeus', 'IMDB Score': '8.3', 'Year of Release': '1984'},
{'title': 'Amélie', 'IMDB Score': '8.3', 'Year of Release': '2001'},
{'title': 'A Clockwork Orange', 'IMDB Score': '8.3', 'Year of Release': '1971'},
{'title': 'Lawrence of Arabia', 'IMDB Score': '8.3', 'Year of Release': '1962'},
{'title': 'Eternal Sunshine of the Spotless Mind', 'IMDB Score': '8.3', 'Year of Release': '2004'},
{'title': 'Double Indemnity', 'IMDB Score': '8.3', 'Year of Release': '1944'},
{'title': 'Taxi Driver', 'IMDB Score': '8.3', 'Year of Release': '1976'},
{'title': "Singin' in the Rain", 'IMDB Score': '8.3', 'Year of Release': '1952'},
{'title': '2001: A Space Odyssey', 'IMDB Score': '8.3', 'Year of Release': '1968'},
{'title': '3 Idiots', 'IMDB Score': '8.3', 'Year of Release': '2009'},
{'title': 'To Kill a Mockingbird', 'IMDB Score': '8.3', 'Year of Release': '1962'},
{'title': 'Toy Story', 'IMDB Score': '8.3', 'Year of Release': '1995'},
{'title': 'Full Metal Jacket', 'IMDB Score': '8.3', 'Year of Release': '1987'},
{'title': 'Inglourious Basterds', 'IMDB Score': '8.3', 'Year of Release': '2009'},
{'title': 'The Sting', 'IMDB Score': '8.3', 'Year of Release': '1973'},
{'title': 'Bicycle Thieves', 'IMDB Score': '8.3', 'Year of Release': '1948'},
{'title': 'The Kid', 'IMDB Score': '8.3', 'Year of Release': '1921'},
{'title': 'Toy Story 3', 'IMDB Score': '8.3', 'Year of Release': '2010'},
{'title': 'Snatch', 'IMDB Score': '8.3', 'Year of Release': '2000'},
{'title': 'Good Will Hunting', 'IMDB Score': '8.3', 'Year of Release': '1997'},
{'title': 'The Hunt', 'IMDB Score': '8.3', 'Year of Release': '2012'},
{'title': 'Monty Python and the Holy Grail', 'IMDB Score': '8.3', 'Year of Release': '1975'},
{'title': 'For a Few Dollars More', 'IMDB Score': '8.3', 'Year of Release': '1965'},
{'title': 'Scarface', 'IMDB Score': '8.2', 'Year of Release': '1983'},
{'title': 'L.A. Confidential', 'IMDB Score': '8.2', 'Year of Release': '1997'},
{'title': 'The Apartment', 'IMDB Score': '8.2', 'Year of Release': '1960'},
{'title': 'Metropolis', 'IMDB Score': '8.2', 'Year of Release': '1927'},
{'title': 'A Separation', 'IMDB Score': '8.2', 'Year of Release': '2011'},
{'title': 'Rashomon', 'IMDB Score': '8.2', 'Year of Release': '1950'},
{'title': 'Indiana Jones and the Last Crusade', 'IMDB Score': '8.2', 'Year of Release': '1989'},
{'title': 'Up', 'IMDB Score': '8.2', 'Year of Release': '2009'},
{'title': 'Yojimbo', 'IMDB Score': '8.2', 'Year of Release': '1961'},
{'title': 'All About Eve', 'IMDB Score': '8.2', 'Year of Release': '1950'},
{'title': 'Batman Begins', 'IMDB Score': '8.2', 'Year of Release': '2005'},
{'title': 'Some Like It Hot', 'IMDB Score': '8.2', 'Year of Release': '1959'},
{'title': 'Unforgiven', 'IMDB Score': '8.2', 'Year of Release': '1992'},
{'title': 'The Treasure of the Sierra Madre', 'IMDB Score': '8.2', 'Year of Release': '1948'},
{'title': 'My Father and My Son', 'IMDB Score': '8.2', 'Year of Release': '2005'},
{'title': 'Downfall', 'IMDB Score': '8.2', 'Year of Release': '2004'},
{'title': 'Die Hard', 'IMDB Score': '8.2', 'Year of Release': '1988'},
{'title': 'Heat', 'IMDB Score': '8.2', 'Year of Release': '1995'},
{'title': 'Raging Bull', 'IMDB Score': '8.2', 'Year of Release': '1980'},
{'title': 'Three Billboards Outside Ebbing, Missouri', 'IMDB Score': '8.2', 'Year of Release': '2017'},
{'title': 'Ikiru', 'IMDB Score': '8.2', 'Year of Release': '1952'},
{'title': 'The Great Escape', 'IMDB Score': '8.2', 'Year of Release': '1963'},
{'title': 'The Third Man', 'IMDB Score': '8.2', 'Year of Release': '1949'},
{'title': 'Children of Heaven', 'IMDB Score': '8.2', 'Year of Release': '1997'},
{'title': 'Chinatown', 'IMDB Score': '8.2', 'Year of Release': '1974'},
{'title': "Pan's Labyrinth", 'IMDB Score': '8.2', 'Year of Release': '2006'},
{'title': 'Incendies', 'IMDB Score': '8.2', 'Year of Release': '2010'},
{'title': 'My Neighbor Totoro', 'IMDB Score': '8.2', 'Year of Release': '1988'},
{'title': 'Ran', 'IMDB Score': '8.2', 'Year of Release': '1985'},
{'title': 'Judgment at Nuremberg', 'IMDB Score': '8.2', 'Year of Release': '1961'},
{'title': 'The Secret in Their Eyes', 'IMDB Score': '8.2', 'Year of Release': '2009'},
{'title': 'The Gold Rush', 'IMDB Score': '8.2', 'Year of Release': '1925'},
{'title': "Howl's Moving Castle", 'IMDB Score': '8.2', 'Year of Release': '2004'},
{'title': 'The Bridge on the River Kwai', 'IMDB Score': '8.2', 'Year of Release': '1957'},
{'title': 'On the Waterfront', 'IMDB Score': '8.2', 'Year of Release': '1954'},
{'title': 'Inside Out', 'IMDB Score': '8.2', 'Year of Release': '2015'},
{'title': 'The Seventh Seal', 'IMDB Score': '8.2', 'Year of Release': '1957'},
{'title': 'Lock, Stock and Two Smoking Barrels', 'IMDB Score': '8.2', 'Year of Release': '1998'},
{'title': 'A Beautiful Mind', 'IMDB Score': '8.2', 'Year of Release': '2001'},
{'title': 'Casino', 'IMDB Score': '8.2', 'Year of Release': '1995'},
{'title': 'Room', 'IMDB Score': '8.2', 'Year of Release': '2015'},
{'title': 'Mr. Smith Goes to Washington', 'IMDB Score': '8.2', 'Year of Release': '1939'},
{'title': 'The Elephant Man', 'IMDB Score': '8.1', 'Year of Release': '1980'},
{'title': 'Sherlock Jr.', 'IMDB Score': '8.1', 'Year of Release': '1924'},
{'title': 'The Wolf of Wall Street', 'IMDB Score': '8.1', 'Year of Release': '2013'},
{'title': 'V for Vendetta', 'IMDB Score': '8.1', 'Year of Release': '2005'},
{'title': 'Blade Runner', 'IMDB Score': '8.1', 'Year of Release': '1982'},
{'title': 'Wild Strawberries', 'IMDB Score': '8.1', 'Year of Release': '1957'},
{'title': 'The General', 'IMDB Score': '8.1', 'Year of Release': '1926'},
{'title': 'Warrior', 'IMDB Score': '8.1', 'Year of Release': '2011'},
{'title': 'Dial M for Murder', 'IMDB Score': '8.1', 'Year of Release': '1954'},
{'title': 'Trainspotting', 'IMDB Score': '8.1', 'Year of Release': '1996'},
{'title': 'Gone with the Wind', 'IMDB Score': '8.1', 'Year of Release': '1939'},
{'title': 'Gran Torino', 'IMDB Score': '8.1', 'Year of Release': '2008'},
{'title': 'No Country for Old Men', 'IMDB Score': '8.1', 'Year of Release': '2007'},
{'title': 'The Sixth Sense', 'IMDB Score': '8.1', 'Year of Release': '1999'},
{'title': 'Fargo', 'IMDB Score': '8.1', 'Year of Release': '1996'},
{'title': 'The Deer Hunter', 'IMDB Score': '8.1', 'Year of Release': '1978'},
{'title': 'There Will Be Blood', 'IMDB Score': '8.1', 'Year of Release': '2007'},
{'title': 'The Thing', 'IMDB Score': '8.1', 'Year of Release': '1982'},
{'title': 'Finding Nemo', 'IMDB Score': '8.1', 'Year of Release': '2003'},
{'title': 'The Big Lebowski', 'IMDB Score': '8.1', 'Year of Release': '1998'},
{'title': 'Come and See', 'IMDB Score': '8.1', 'Year of Release': '1985'},
{'title': 'Sunrise', 'IMDB Score': '8.1', 'Year of Release': '1927'},
{'title': 'Cool Hand Luke', 'IMDB Score': '8.1', 'Year of Release': '1967'},
{'title': 'Tokyo Story', 'IMDB Score': '8.1', 'Year of Release': '1953'},
{'title': 'Kill Bill: Vol. 1', 'IMDB Score': '8.1', 'Year of Release': '2003'},
{'title': 'Rebecca', 'IMDB Score': '8.1', 'Year of Release': '1940'},
{'title': 'The Bandit', 'IMDB Score': '8.1', 'Year of Release': '1996'},
{'title': 'Andrei Rublev', 'IMDB Score': '8.1', 'Year of Release': '1966'},
{'title': 'Shutter Island', 'IMDB Score': '8.1', 'Year of Release': '2010'},
{'title': 'Hacksaw Ridge', 'IMDB Score': '8.1', 'Year of Release': '2016'},
{'title': 'How to Train Your Dragon', 'IMDB Score': '8.1', 'Year of Release': '2010'},
{'title': 'Blade Runner 2049', 'IMDB Score': '8.1', 'Year of Release': '2017'},
{'title': 'Mary and Max', 'IMDB Score': '8.1', 'Year of Release': '2009'},
{'title': 'Gone Girl', 'IMDB Score': '8.1', 'Year of Release': '2014'},
{'title': 'Into the Wild', 'IMDB Score': '8.1', 'Year of Release': '2007'},
{'title': 'Life of Brian', 'IMDB Score': '8.1', 'Year of Release': '1979'},
{'title': 'Wild Tales', 'IMDB Score': '8.1', 'Year of Release': '2014'},
{'title': 'Rang De Basanti', 'IMDB Score': '8.1', 'Year of Release': '2006'},
{'title': 'It Happened One Night', 'IMDB Score': '8.1', 'Year of Release': '1934'},
{'title': 'The Passion of Joan of Arc', 'IMDB Score': '8.1', 'Year of Release': '1928'},
{'title': 'Platoon', 'IMDB Score': '8.1', 'Year of Release': '1986'},
{'title': 'In the Name of the Father', 'IMDB Score': '8.1', 'Year of Release': '1993'},
{'title': 'Hotel Rwanda', 'IMDB Score': '8.1', 'Year of Release': '2004'},
{'title': 'Network', 'IMDB Score': '8.1', 'Year of Release': '1976'},
{'title': 'Stand by Me', 'IMDB Score': '8.1', 'Year of Release': '1986'},
{'title': 'The Grand Budapest Hotel', 'IMDB Score': '8.1', 'Year of Release': '2014'},
{'title': 'The Wages of Fear', 'IMDB Score': '8.1', 'Year of Release': '1953'},
{'title': 'Stalker', 'IMDB Score': '8.1', 'Year of Release': '1979'},
{'title': 'Ben-Hur', 'IMDB Score': '8.1', 'Year of Release': '1959'},
{'title': 'Jurassic Park', 'IMDB Score': '8.1', 'Year of Release': '1993'},
{'title': 'Rush', 'IMDB Score': '8.1', 'Year of Release': '2013'},
{'title': 'Persona', 'IMDB Score': '8.1', 'Year of Release': '1966'},
{'title': '12 Years a Slave', 'IMDB Score': '8.1', 'Year of Release': '2013'},
{'title': 'Memories of Murder', 'IMDB Score': '8.1', 'Year of Release': '2003'},
{'title': 'Million Dollar Baby', 'IMDB Score': '8.1', 'Year of Release': '2004'},
{'title': 'The Truman Show', 'IMDB Score': '8.1', 'Year of Release': '1998'},
{'title': 'The 400 Blows', 'IMDB Score': '8.1', 'Year of Release': '1959'},
{'title': 'Mad Max: Fury Road', 'IMDB Score': '8.1', 'Year of Release': '2015'},
{'title': 'Spotlight', 'IMDB Score': '8.1', 'Year of Release': '2015'},
{'title': 'Logan', 'IMDB Score': '8.1', 'Year of Release': '2017'},
{'title': 'Amores Perros', 'IMDB Score': '8.1', 'Year of Release': '2000'},
{'title': 'Before Sunrise', 'IMDB Score': '8.1', 'Year of Release': '1995'},
{'title': "Hachi: A Dog's Tale", 'IMDB Score': '8.1', 'Year of Release': '2009'},
{'title': 'Butch Cassidy and the Sundance Kid', 'IMDB Score': '8.1', 'Year of Release': '1969'},
{'title': 'La La Land', 'IMDB Score': '8.1', 'Year of Release': '2016'},
{'title': 'Nausicaä of the Valley of the Wind', 'IMDB Score': '8.1', 'Year of Release': '1984'},
{'title': 'The Princess Bride', 'IMDB Score': '8.1', 'Year of Release': '1987'},
{'title': 'Prisoners', 'IMDB Score': '8.0', 'Year of Release': '2013'},
{'title': 'A Wednesday', 'IMDB Score': '8.0', 'Year of Release': '2008'},
{'title': 'The Maltese Falcon', 'IMDB Score': '8.0', 'Year of Release': '1941'},
{'title': 'Catch Me If You Can', 'IMDB Score': '8.0', 'Year of Release': '2002'},
{'title': 'Harry Potter and the Deathly Hallows: Part 2', 'IMDB Score': '8.0', 'Year of Release': '2011'},
{'title': 'Rocky', 'IMDB Score': '8.0', 'Year of Release': '1976'},
{'title': 'The Nights of Cabiria', 'IMDB Score': '8.0', 'Year of Release': '1957'},
{'title': 'The Grapes of Wrath', 'IMDB Score': '8.0', 'Year of Release': '1940'},
{'title': 'Monsters, Inc.', 'IMDB Score': '8.0', 'Year of Release': '2001'},
{'title': 'Diabolique', 'IMDB Score': '8.0', 'Year of Release': '1955'},
{'title': 'Donnie Darko', 'IMDB Score': '8.0', 'Year of Release': '2001'},
{'title': 'Barry Lyndon', 'IMDB Score': '8.0', 'Year of Release': '1975'},
{'title': 'Gandhi', 'IMDB Score': '8.0', 'Year of Release': '1982'},
{'title': 'Paper Moon', 'IMDB Score': '8.0', 'Year of Release': '1973'},
{'title': 'Touch of Evil', 'IMDB Score': '8.0', 'Year of Release': '1958'},
{'title': 'The Terminator', 'IMDB Score': '8.0', 'Year of Release': '1984'},
{'title': 'La Haine', 'IMDB Score': '8.0', 'Year of Release': '1995'},
{'title': 'Groundhog Day', 'IMDB Score': '8.0', 'Year of Release': '1993'},
{'title': 'The Wizard of Oz', 'IMDB Score': '8.0', 'Year of Release': '1939'},
{'title': 'The Bourne Ultimatum', 'IMDB Score': '8.0', 'Year of Release': '2007'},
{'title': 'Annie Hall', 'IMDB Score': '8.0', 'Year of Release': '1977'},
{'title': 'Dead Poets Society', 'IMDB Score': '8.0', 'Year of Release': '1989'},
{'title': '8½', 'IMDB Score': '8.0', 'Year of Release': '1963'},
{'title': 'Jaws', 'IMDB Score': '8.0', 'Year of Release': '1975'},
{'title': 'The Help', 'IMDB Score': '8.0', 'Year of Release': '2011'},
{'title': 'In the Mood for Love', 'IMDB Score': '8.0', 'Year of Release': '2000'},
{'title': 'The Best Years of Our Lives', 'IMDB Score': '8.0', 'Year of Release': '1946'},
{'title': 'Infernal Affairs', 'IMDB Score': '8.0', 'Year of Release': '2002'},
{'title': 'Paris, Texas', 'IMDB Score': '8.0', 'Year of Release': '1984'},
{'title': 'Twelve Monkeys', 'IMDB Score': '8.0', 'Year of Release': '1995'},
{'title': 'Tangerines', 'IMDB Score': '8.0', 'Year of Release': '2013'},
{'title': 'Beauty and the Beast', 'IMDB Score': '8.0', 'Year of Release': '1991'},
{'title': 'Three Colors: Red', 'IMDB Score': '8.0', 'Year of Release': '1994'},
{'title': 'Before Sunset', 'IMDB Score': '8.0', 'Year of Release': '2004'},
{'title': 'Dog Day Afternoon', 'IMDB Score': '8.0', 'Year of Release': '1975'},
{'title': 'The Battle of Algiers', 'IMDB Score': '8.0', 'Year of Release': '1966'},]

APIT = [ 
{'name' : 'Year of Release', 'is_num' : True},
{'name' : 'IMDB Score', 'is_num' : True}]