# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 04:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteriaName', models.CharField(default='', max_length=100)),
                ('criteriaWeight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Decide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default='', max_length=100)),
                ('itemScore', models.IntegerField(default=0)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='decisions.Decide')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='First', max_length=100)),
                ('lastName', models.CharField(default='Last', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(13)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other'), (None, 'Prefer not to answer')], max_length=25, null=True)),
                ('income', models.PositiveIntegerField(blank=True, null=True)),
                ('race', models.CharField(blank=True, choices=[('American Indian or Alaskan Native', 'American Indian or Alaskan Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('White', 'White'), (None, 'Prefer not to answer')], max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('Hispanic or Latino', 'Hispanic or Latino'), ('Not Hispanic or Latino', 'Not Hispanic or Latino'), (None, 'Prefer not to answer')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='decide',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.UserProfile'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='decisions.Decide'),
        ),
    ]
