# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='criteria_list',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='item_list',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='name',
        ),
        migrations.AddField(
            model_name='decision',
            name='criteria1',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='criteria2',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='criteria3',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='cw1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='cw2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='cw3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i1c1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i1c2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i1c3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i2c1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i2c2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i2c3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i3c1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i3c2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='i3c3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='item1',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='item2',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='item3',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='your_decision',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
