# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decisions', '0002_auto_20171019_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_decision', models.CharField(default=b'', max_length=100)),
                ('item1', models.CharField(default=b'', max_length=100)),
                ('item2', models.CharField(default=b'', max_length=100)),
                ('item3', models.CharField(default=b'', max_length=100)),
                ('criteria1', models.CharField(default=b'', max_length=100)),
                ('criteria2', models.CharField(default=b'', max_length=100)),
                ('criteria3', models.CharField(default=b'', max_length=100)),
                ('cw1', models.IntegerField(default=0)),
                ('cw2', models.IntegerField(default=0)),
                ('cw3', models.IntegerField(default=0)),
                ('i1c1', models.IntegerField(default=0)),
                ('i1c2', models.IntegerField(default=0)),
                ('i1c3', models.IntegerField(default=0)),
                ('i2c1', models.IntegerField(default=0)),
                ('i2c2', models.IntegerField(default=0)),
                ('i2c3', models.IntegerField(default=0)),
                ('i3c1', models.IntegerField(default=0)),
                ('i3c2', models.IntegerField(default=0)),
                ('i3c3', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
