# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0009_userdecision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdecision',
            old_name='user',
            new_name='user_profile',
        ),
    ]
