# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0010_auto_20171103_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdecision',
            name='firstPlace',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='userdecision',
            name='secondPlace',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='userdecision',
            name='thirdPlace',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
