# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0011_auto_20171106_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(default='', max_length=100)),
                ('criteria_weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Decide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=100)),
                ('item_score', models.IntegerField(default=0)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Decide')),
            ],
        ),
        migrations.AlterField(
            model_name='decision',
            name='criteria1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='criteria2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='criteria3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='item1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='item2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='item3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='your_decision',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='criteria1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='criteria2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='criteria3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='firstPlace',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='item1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='item2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='item3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='secondPlace',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='thirdPlace',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdecision',
            name='your_decision',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='criteria',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Decide'),
        ),
    ]
