# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0012_auto_20171109_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='criteria_name',
            new_name='criteriaName',
        ),
        migrations.RenameField(
            model_name='criteria',
            old_name='criteria_weight',
            new_name='criteriaWeight',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_score',
            new_name='itemScore',
        ),
    ]
