# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0013_auto_20171113_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='decide',
            name='user_profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='decisions.UserProfile'),
            preserve_default=False,
        ),
    ]
