# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0017_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decision',
        ),
        migrations.RemoveField(
            model_name='userdecision',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='UserDecision',
        ),
    ]
