# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0019_auto_20180227_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='income',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='race',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(default='First name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default='Last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='State', max_length=100),
        ),
    ]
