# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 17:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0020_auto_20180228_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(13)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('Hispanic or Latino', 'Hispanic or Latino'), ('Not Hispanic or Latino', 'Not Hispanic or Latino'), (None, 'Prefer not to answer')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other'), (None, 'Prefer not to answer')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='race',
            field=models.CharField(blank=True, choices=[('American Indian or Alaskan Native', 'American Indian or Alaskan Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('White', 'White'), (None, 'Prefer not to answer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(default='First', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default='Last', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
